[FFT]	- trying to resolve this error "error C2676: binary '*': 'T' does not define this operator or a conversion to a type acceptable to the predefined operator"