Problem: error C2398: Element '3': conversion from 'unsigned long' to 'long' requires a narrowing conversion error C2398: Element '4': conversion from 'unsigned long' to 'long' requires a narrowing conversion error C2398: Element '6': conversion from 'unsigned long' to 'long' requires a narrowing conversion error C2398: Element '7': conversion from 'unsigned long' to 'long' requires a narrowing conversion error C2398: Element '8': conversion from 'unsigned long' to 'long' requires a narrowing conversion error C2398: Element '9': conversion from 'unsigned long' to 'long' requires a narrowing conversion ...
Solution: explicitly use `unsigned long`